### ISSUE TITLE
[BUG] operate > AttributeError: dlsym(0x3c3fe83b0, objc_msgSendSuper_stret): symbol not found

### ISSUE THREAD

**Issue by exgbit** [OthersideAI/self-operating-computer#130]
(venv) (base) justin self-operating-computer % operate                                               
Traceback (most recent call last):
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/bin/operate", line 7, in <module>
    from operate.main import main_entry
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/operate/main.py", line 6, in <module>
    from operate.dialog import main
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/operate/dialog.py", line 19, in <module>
    from operate.utils.os import (
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/operate/utils/os.py", line 1, in <module>
    import pyautogui
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/mouseinfo/__init__.py", line 100, in <module>
    from rubicon.objc import ObjCClass, CGPoint
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/rubicon/objc/__init__.py", line 33, in <module>
    from . import api, collections, runtime, types
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/rubicon/objc/api.py", line 29, in <module>
    from .runtime import (
  File "/Users/justin/Library/CloudStorage/Dropbox/Mac (3)/Desktop/code/self-operating-computer/venv/lib/python3.11/site-packages/rubicon/objc/runtime.py", line 460, in <module>
    libobjc.objc_msgSendSuper_stret.restype = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justin/miniconda3/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justin/miniconda3/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: dlsym(0x3c3fe83b0, objc_msgSendSuper_stret): symbol not found

**Comment by exgbit** [comment]
Apple M2 Max M2 Sonoma 14.2.1

**Comment by Neminem-HC** [comment]
I have a similar error using Apple M2 14.2.1. I figured out that this is caused by pyautogui and more precise in the rubicon module. But this error only occurs when I am packaging the python script with pyinstaller. Did you also converted you script into an executable? For me the executable also runs normally when it's in the path of /Users/your_user. I can't get it to work. I tried excluding the rubicon module in the pyinstaller but than pyautogui doesn't work anymore.  

Here is my full log:

Traceback (most recent call last):
  File "v2.py", line 5, in <module>
    import pyautogui
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pyautogui/__init__.py", line 246, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "mouseinfo/__init__.py", line 100, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "rubicon/objc/__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "rubicon/objc/api.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "rubicon/objc/runtime.py", line 460, in <module>
  File "ctypes/__init__.py", line 392, in __getattr__
  File "ctypes/__init__.py", line 397, in __getitem__
AttributeError: dlsym(0x3c04283b0, objc_msgSendSuper_stret): symbol not found
[16526] Failed to execute script 'v2' due to unhandled exception!

Hope to find a solution...

**Comment by PyyTom** [comment]
Hello same problem here...

**Comment by crossxx-labs** [comment]
It's a pyobjc issue. I switched to python3.8 and re-installed pyobjc from git repo,  then the error disappeared. [Details here](https://github.com/asweigart/pyautogui/issues/772#issuecomment-1931241870)
