### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by lescratheurjar** [OthersideAI/self-operating-computer#177]
### Describe the bug

When is launch “operate”, the console gives an error message :
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\quent\AppData\Local\Programs\Python\Python312\Scripts\operate.exe\__main__.py", line 4, in <module>
  File "C:\Users\quent\AppData\Local\Programs\Python\Python312\Lib\site-packages\operate\main.py", line 6, in <module>
    from operate.operate import main
  File "C:\Users\quent\AppData\Local\Programs\Python\Python312\Lib\site-packages\operate\operate.py", line 26, in <module>
    from operate.models.apis import get_next_action
  File "C:\Users\quent\AppData\Local\Programs\Python\Python312\Lib\site-packages\operate\models\apis.py", line 32, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

### Environment
- OS: Windows
- Model Used (e.g., GPT-4v, Gemini Pro Vision): GPT-3.5

**Comment by lescratheurjar** [comment]
I fix the bug (just reinstall your files "operate")

**Comment by KISHAN8888** [comment]
just reinstall the setuptools package by running the command pip install --upgrade setuptools
 this worked for me!!

**Comment by ingenuousmorpheus** [comment]
pip install setuptools   :-) ive been stuck on this same problem for 2 months and literally used ai to walk me through it just to discove thats what I was missing from the operate install. it is working on windows. its hard to find people doing tutorials for windows pcs.

**Comment by jimmon89** [comment]
on cachyOS(an arch derivative) i am getting this error using pyenv with python 3.11 AND 3.12, and this command doesn't help on either.
--EDIT--
same effect with both the AUR package, cachyOS package, and the manual version
